#使用@ @引用maven中定义的属性，springboot屏蔽默认maven资源占位符$ $,并修改为@ @
spring:
  profiles:
    active: @profiles.active@

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/myitem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123
#  jpa:
#    #配置数据库引擎和字符集
#    properties:
#      hibernate:
#        dialect: ymx.example.myitem.config.MySQL5TableType
#    #配置自动建表：updata:没有表新建，有表更新操作
#    hibernate:
#      ddl-auto: update
#    #控制台显示建表语句
#    show-sql: true
#  thymeleaf:
#    #关闭模板缓存
#    cache: false